version: "3"

services:
  post:
    build: ./post
    environment:
      - HOST=0.0.0.0
      - PORT=31337

  post-page:
    build: ./post-page
    environment:
      - POST_HOST=post
      - POST_PORT=31337
    depends_on:
      - post

  gateway:
    build: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - post-page