version: "3"

services:
  post:
    build: ./post
    environment:
      - HOST=0.0.0.0
      - PORT=31337
    ports:
      - "31337:31337"

  post-page:
    build: ./post-page
    ports:
      - "8080:8080"
    environment:
      - POST_HOST=post
      - POST_PORT=31337
    depends_on:
      - post
