version: "3"

services:
  consul:
    image: consul:1.0.6
    ports:
      - "8500:8500"

  post:
    build: ./post
    environment:
      - PORT=31337
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul

  post-page:
    build: ./post-page
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - post
      - consul

  gateway:
    build: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - post-page